variables:
  PROJ_NAME: commander-center
  IMAGE_NAME: dpsp-command-on-call-frontend
  NAMESPACE: dpsp-command-on-call

include:
  - project: grupo-dpsp/devops/pipeline-cicd-base
    ref: main
    file: devops-gitlab-ci-frontend.yaml
