variables:
  PROJ_NAME: command-on-call
  IMAGE_NAME: $CI_PROJECT_NAME
  NAMESPACE: dpsp-command-on-call

include:
  - project: grupo-dpsp/devops/platform-engineering/ci-templates
    ref: main
    file: pipelines/frontend-docker.yml